# Generated by Django 3.2 on 2021-04-15 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='loacation',
            new_name='location',
        ),
    ]
