# Generated by Django 3.2 on 2021-04-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_rename_loacation_userprofile_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='static/covid/userImage')),
            ],
        ),
    ]
