# Generated by Django 3.2 on 2021-05-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0007_alter_userimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=50)),
                ('xcoord', models.FloatField()),
                ('ycoord', models.FloatField()),
                ('fee', models.IntegerField()),
            ],
        ),
    ]
