# Generated by Django 3.2 on 2021-05-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0008_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fee',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='xcoord',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ycoord',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
