# Generated by Django 3.2 on 2021-05-16 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0009_auto_20210516_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='fee',
        ),
    ]
