# Generated by Django 3.2 on 2021-05-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0010_remove_userprofile_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fee',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
